services:
  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION:-latest}
    container_name: prometheus
    restart: unless-stopped
    ports:
      - '${PROMETHEUS_PORT:-9090}:9090'
    volumes:
      - './config/prometheus:/etc/prometheus'
      - 'prometheus_storage:/prometheus'

  grafana:
    image: grafana/grafana-oss:${GRAFANA_VERSION:-latest}
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_SERVER_ROOT_URL=${GRAFANA_HOST}
      - GF_INSTALL_PLUGINS=${GRAFANA_PLUGINS}
    ports:
      - '${GRAFANA_PORT:-3000}:3000'
    volumes:
      - './config/grafana:/etc/grafana/provisioning/datasources'
      - 'grafana_storage:/var/lib/grafana'

volumes:
  grafana_storage: {}
  prometheus_storage: {}